import type { Metadata } from "next";
import "../style/globals.css";
import GsapPluginRegisterWrapper from "@/lib/gsap/GsapPluginRegisterWrapper";
import AnimatePresenceContextProvider from "@/lib/framerMotion/AnimatePresenceContextProvider";
import { headers } from "next/headers";
import { langQueryHeaderName } from "@/contents/supportedLanguagesData";
import FixedHeader from "@/components/header/FixedHeader";
import BlankLoadingContextProvider from "@/components/loader/BlankLoadingContextProvider";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    formatDetection: {
        email: false,
        address: false,
        telephone: false,
    },
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode; 
}>) {
    const headerList = await headers();
    const lang = headerList.get(langQueryHeaderName) ?? "en";
    return (
        <html lang={lang} >
            <body>
                
                <BlankLoadingContextProvider>
                    <FixedHeader />
                    <GsapPluginRegisterWrapper>
                        
                            <AnimatePresenceContextProvider pageTransitionType="FullScreenSlide" mode="popLayout">
                                {children}
                            </AnimatePresenceContextProvider>
                     
                    </GsapPluginRegisterWrapper>
                </BlankLoadingContextProvider>
            </body>
        </html>
    );
}
