import type { Metadata } from "next";
import "../style/globals.css";
import ScrollTriggerRegisterWrapper from "@/lib/gsap/ScrollTriggerRegisterWrapper";
import SmoothScrollRegisterContextProvider from "@/lib/gsap/SmoothScrollRegisterContextProvider";
import AnimatePresenceContextProvider from "@/lib/framerMotion/AnimatePresenceContextProvider";
import { headers } from "next/headers";
import { langQueryHeaderName } from "@/contents/supportedLanguagesData";
import FixedHeader from "@/components/header/FixedHeader";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const headerList = await headers();
    const lang = headerList.get(langQueryHeaderName) ?? "en";
    return (
        <html lang={lang} >
            <body>
                <FixedHeader />
                <ScrollTriggerRegisterWrapper>
                    <SmoothScrollRegisterContextProvider>
                        <AnimatePresenceContextProvider pageTransitionType="none">
                            {children}
                        </AnimatePresenceContextProvider>
                    </SmoothScrollRegisterContextProvider>
                </ScrollTriggerRegisterWrapper>
            </body>
        </html>
    );
}
