import type { Metadata } from "next";
import "../style/globals.css";
import GsapPluginRegisterWrapper from "@/lib/gsap/GsapPluginRegisterWrapper";
import SmoothScrollRegisterContextProvider from "@/lib/gsap/SmoothScrollRegisterContextProvider";
import AnimatePresenceContextProvider from "@/lib/framerMotion/AnimatePresenceContextProvider";
import { headers } from "next/headers";
import { langQueryHeaderName } from "@/contents/supportedLanguagesData";
import FixedHeader from "@/components/header/FixedHeader";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    formatDetection: {
        email: false,
        address: false,
        telephone: false,
    },
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode; 
}>) {
    const headerList = await headers();
    const lang = headerList.get(langQueryHeaderName) ?? "en";
    return (
        <html lang={lang} >
            <body>
                <FixedHeader />
                <GsapPluginRegisterWrapper>
                    <SmoothScrollRegisterContextProvider>
                        <AnimatePresenceContextProvider pageTransitionType="FullScreenSlide" mode="popLayout">
                            {children}
                        </AnimatePresenceContextProvider>
                    </SmoothScrollRegisterContextProvider>
                </GsapPluginRegisterWrapper>
            </body>
        </html>
    );
}
